name: digital-ocean-deploy

on:
  workflow_call:
    inputs:
      image_name:
        description: "Image Name"
        required: true
        type: string

      docker_container_name:
        description: "Docker container Name"
        required: true
        type: string

      do_host:
        description: "Digital Ocean host"
        required: true
        type: string

      do_username:
        description: "Digital Ocean username"
        required: true
        type: string

      docker_port_mapping:
        description: "Docker port mapping"
        required: false
        type: number

    secrets:
      do_ssh_key:
        description: "Docker Hub token"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  digital-ocean-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name }}

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ inputs.do_host }}
          username: ${{ inputs.do_username }}
          key: ${{ secrets.do_ssh_key }}
          script: |
            IMAGE="${{ inputs.image_name }}"
            NEW_CONTAINER="${{ inputs.docker_container_name }}-new"
            OLD_CONTAINER="${{ inputs.docker_container_name }}"

            echo "Pull image"
            docker pull $IMAGE

            echo "Start new container"
            docker run -d \
              --name $NEW_CONTAINER \
              -p $(if [ "${{ inputs.docker_port_mapping }}" ]; then echo ${{ inputs.docker_port_mapping }}; else echo 8000; fi):8000 \
              --restart always \
              $IMAGE

            echo "Wait for container to boot"
            sleep 10

            if [ "$(docker inspect -f '{{.State.Running}}' $NEW_CONTAINER)" != "true" ]; then
              echo "New container failed to start. Rolling back."
              docker rm -f $NEW_CONTAINER
              exit 1
            fi

            echo "Stop old container"
            docker rm -f $OLD_CONTAINER || true

            echo "Rename new container"
            docker rename $NEW_CONTAINER $OLD_CONTAINER

            echo "Cleanup old images"
            docker image prune -f
