name: do-deploy-no-dh

on:
  workflow_call:
    inputs:
      docker_container_name:
        description: "Docker container Name"
        required: true
        type: string
      do_host:
        description: "Digital Ocean host"
        required: true
        type: string
      do_username:
        description: "Digital Ocean username"
        required: true
        type: string
      git_project_name:
        description: "Git repo name"
        required: true
        type: string
    secrets:
      do_ssh_key:
        description: "Docker Hub token"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  digital-ocean-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name }}

    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: read var
        run: |
          echo "inputs.docker_container_name ${{ inputs.docker_container_name }}"
          echo "inputs.do_username ${{ inputs.do_username }}"
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ inputs.do_host }}
          username: ${{ inputs.do_username }}
          key: ${{ secrets.do_ssh_key }}
          script: |

            #Create a folder repos
            mkdir -p repos
            cd repos
            #Delete previous project folder
            if [ -d "${{ inputs.git_project_name }}" ]; then
              cd ${{ inputs.git_project_name }}
              docker compose down --rmi all
              cd ../
              rm -rf ${{ inputs.git_project_name }}
            fi

            #Clone a new one
            git clone git@github.com:yuri-kazliak/${{ inputs.git_project_name }}.git
            cd ${{ inputs.git_project_name }}
            docker compose up -d
